
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package enchia.time.main.init;

import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ColorHandlerEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import java.util.List;
import java.util.ArrayList;

import enchia.time.main.block.YellowMushroomBlock;
import enchia.time.main.block.YellowGlassDoorBlock;
import enchia.time.main.block.XpaltarBlock;
import enchia.time.main.block.XpBlockoBlock;
import enchia.time.main.block.XpBlockOfInfinityBlock;
import enchia.time.main.block.XPLordStatueBlock;
import enchia.time.main.block.WoodsiaBlock;
import enchia.time.main.block.WitherBoneOreBlock;
import enchia.time.main.block.WindSandBlock;
import enchia.time.main.block.WindGlassBlock;
import enchia.time.main.block.WhitediamondOreBlockBlock;
import enchia.time.main.block.WhitediamondOreBlock;
import enchia.time.main.block.WhiteRuzovaBlock;
import enchia.time.main.block.WhiteGlowstoneBlock;
import enchia.time.main.block.WhiteGlassDoorBlock;
import enchia.time.main.block.WhiteCrystalBlock;
import enchia.time.main.block.WasteBlockBlock;
import enchia.time.main.block.WaffleStickBlock;
import enchia.time.main.block.VitreousOreBlock;
import enchia.time.main.block.VitreousBlockBlock;
import enchia.time.main.block.UselessTimeMachineBlock;
import enchia.time.main.block.UnluckyBlockBlock;
import enchia.time.main.block.TurtleheadBlock;
import enchia.time.main.block.Trap2Block;
import enchia.time.main.block.Trap1Block;
import enchia.time.main.block.TinOreBlockBlock;
import enchia.time.main.block.TinOreBlock;
import enchia.time.main.block.TimemachinewalllightBlock;
import enchia.time.main.block.TimeMachineWallBlock;
import enchia.time.main.block.TimeMachineBlockBlock;
import enchia.time.main.block.TimeMachineBlock;
import enchia.time.main.block.TimeGemOreBlock;
import enchia.time.main.block.TimeChaosMachineBlock;
import enchia.time.main.block.TerameriaiumoreBlock;
import enchia.time.main.block.TeleportCakeBlock;
import enchia.time.main.block.TeakPressurePlateBlock;
import enchia.time.main.block.TeakPlanksButtonBlock;
import enchia.time.main.block.TeakBookshelfBlock;
import enchia.time.main.block.SweetGrassBlock;
import enchia.time.main.block.StrawberryPlanksButtonBlock;
import enchia.time.main.block.StrawberryLogWoodBlock;
import enchia.time.main.block.StrawberryLogStairsBlock;
import enchia.time.main.block.StrawberryLogSlabBlock;
import enchia.time.main.block.StrawberryLogPlanksBlock;
import enchia.time.main.block.StrawberryLogLogBlock;
import enchia.time.main.block.StrawberryLogLeavesBlock;
import enchia.time.main.block.StrawberryLogFenceGateBlock;
import enchia.time.main.block.StrawberryLogFenceBlock;
import enchia.time.main.block.StrawberryBlockBlock;
import enchia.time.main.block.StrawberriesPlantBlock;
import enchia.time.main.block.StoneOfTheDepthsBlock;
import enchia.time.main.block.StoneGrassBlock;
import enchia.time.main.block.SpringOreBlock;
import enchia.time.main.block.SpringBlock;
import enchia.time.main.block.Spring3Block;
import enchia.time.main.block.Spring2Block;
import enchia.time.main.block.SpawnDungeon25600BlockBlock;
import enchia.time.main.block.SpaceGemOreBlock;
import enchia.time.main.block.SnowyBlockBlock;
import enchia.time.main.block.SnowSandBlock;
import enchia.time.main.block.SnowGlassBlock;
import enchia.time.main.block.SmoothBlockBlock;
import enchia.time.main.block.SilentiaGrassBlock;
import enchia.time.main.block.SilentiaDirtBlock;
import enchia.time.main.block.ShurbBlock;
import enchia.time.main.block.SeaweedsDryerBlock;
import enchia.time.main.block.ScrollBenchBlock;
import enchia.time.main.block.Sandstone9Block;
import enchia.time.main.block.Sandstone8Block;
import enchia.time.main.block.Sandstone7Block;
import enchia.time.main.block.Sandstone6Block;
import enchia.time.main.block.Sandstone5Block;
import enchia.time.main.block.Sandstone4Block;
import enchia.time.main.block.Sandstone3Block;
import enchia.time.main.block.Sandstone2Block;
import enchia.time.main.block.Sandstone1Block;
import enchia.time.main.block.Sandstone10Block;
import enchia.time.main.block.SandTrap3Block;
import enchia.time.main.block.SandTrap2Block;
import enchia.time.main.block.SandTrap1Block;
import enchia.time.main.block.SandBlock1Block;
import enchia.time.main.block.SandAltarBlock;
import enchia.time.main.block.Sand2Block;
import enchia.time.main.block.Sand102400Block;
import enchia.time.main.block.SakuraWoodBlock;
import enchia.time.main.block.SakuraTrapdoorBlock;
import enchia.time.main.block.SakuraStairsBlock;
import enchia.time.main.block.SakuraSlabBlock;
import enchia.time.main.block.SakuraPressurePlateBlock;
import enchia.time.main.block.SakuraPlanksBlock;
import enchia.time.main.block.SakuraLogBlock;
import enchia.time.main.block.SakuraLeavesBlock;
import enchia.time.main.block.SakuraFenceGateBlock;
import enchia.time.main.block.SakuraFenceBlock;
import enchia.time.main.block.SakuraDoorBlock;
import enchia.time.main.block.SakuraButtonBlock;
import enchia.time.main.block.RuneOreBlock;
import enchia.time.main.block.RuneGrassBlock;
import enchia.time.main.block.RiserStatueBlock;
import enchia.time.main.block.RiserLootBlock;
import enchia.time.main.block.RiserAltarBlock;
import enchia.time.main.block.RedMushroomBlock;
import enchia.time.main.block.RedGlowstoneBlock;
import enchia.time.main.block.RedGlassDoorBlock;
import enchia.time.main.block.RedEternalRedstoneLampBlock;
import enchia.time.main.block.RedCrystalBlock;
import enchia.time.main.block.RandomBlockBlock;
import enchia.time.main.block.RadomblockoBlock;
import enchia.time.main.block.QuartzBlock;
import enchia.time.main.block.Quartz6Block;
import enchia.time.main.block.Quartz4Block;
import enchia.time.main.block.Quartz3Block;
import enchia.time.main.block.Quartz2Block;
import enchia.time.main.block.Quartz1Block;
import enchia.time.main.block.PurplppeGlowstoneBlock;
import enchia.time.main.block.PurpleSandstoneBlock;
import enchia.time.main.block.PurpleGlassDoorBlock;
import enchia.time.main.block.PurpleEternalRedstoneLampBlock;
import enchia.time.main.block.PurpleCutSandstoneBlock;
import enchia.time.main.block.PureWaterBlock;
import enchia.time.main.block.PrairieSageBlock;
import enchia.time.main.block.PolymerizationAltarBlock;
import enchia.time.main.block.Planks9Block;
import enchia.time.main.block.Planks8Block;
import enchia.time.main.block.Planks7Block;
import enchia.time.main.block.Planks5Block;
import enchia.time.main.block.Planks3Block;
import enchia.time.main.block.Planks2Block;
import enchia.time.main.block.Planks1Block;
import enchia.time.main.block.Planks10Block;
import enchia.time.main.block.PinkSandstoneBlock;
import enchia.time.main.block.PinkSandBlock;
import enchia.time.main.block.PinkGlowstoneBlock;
import enchia.time.main.block.PinkGlassDoorBlock;
import enchia.time.main.block.PinkEternalRedstoneLampBlock;
import enchia.time.main.block.PinkCutSandstoneBlock;
import enchia.time.main.block.PinkCrystalBlock;
import enchia.time.main.block.PhantomLogBlock;
import enchia.time.main.block.PhantomLeavesBlock;
import enchia.time.main.block.PerafriumOreBlock;
import enchia.time.main.block.OriginMegmaBlock;
import enchia.time.main.block.OrangeGlassDoorBlock;
import enchia.time.main.block.OrangeEternalRedstoneLampBlock;
import enchia.time.main.block.OldSandBlock;
import enchia.time.main.block.NewDreamBedBlock;
import enchia.time.main.block.NetherreactorBlock;
import enchia.time.main.block.Netherreactor2Block;
import enchia.time.main.block.NetheronoreBlock;
import enchia.time.main.block.NetherancientPortalBlock;
import enchia.time.main.block.NetherGrassBlock;
import enchia.time.main.block.NetherDirtBlock;
import enchia.time.main.block.MysdoorinvkeyneedblockoBlock;
import enchia.time.main.block.MysdoorinvableblockoBlock;
import enchia.time.main.block.MushrooooooomBlock;
import enchia.time.main.block.MushroomtreegreenBlock;
import enchia.time.main.block.MushroomtreeblueBlock;
import enchia.time.main.block.MushroomlogBlock;
import enchia.time.main.block.MushroomSandBlock;
import enchia.time.main.block.MushroomLampBlock;
import enchia.time.main.block.MushroomGlassBlock;
import enchia.time.main.block.MudBlockBlock;
import enchia.time.main.block.MossyStoneBlock;
import enchia.time.main.block.MossyCobbleStoneBlock;
import enchia.time.main.block.MorcantOreBlockBlock;
import enchia.time.main.block.MorcantOreBlock;
import enchia.time.main.block.MoonWarpWoodBlock;
import enchia.time.main.block.MoonWarpStairsBlock;
import enchia.time.main.block.MoonWarpSlabBlock;
import enchia.time.main.block.MoonWarpPressurePlateBlock;
import enchia.time.main.block.MoonWarpPlanksBlock;
import enchia.time.main.block.MoonWarpLogBlock;
import enchia.time.main.block.MoonWarpLeavesBlock;
import enchia.time.main.block.MoonWarpFenceGateBlock;
import enchia.time.main.block.MoonWarpFenceBlock;
import enchia.time.main.block.MoonWarpButtonBlock;
import enchia.time.main.block.MoonPlanksButtonBlock;
import enchia.time.main.block.MoonPlanksBlock;
import enchia.time.main.block.MoonLogBlock;
import enchia.time.main.block.MoonLeavesBlock;
import enchia.time.main.block.MoonGrassBlock;
import enchia.time.main.block.MoonGrass5Block;
import enchia.time.main.block.MoonGrass4Block;
import enchia.time.main.block.MoonGrass3Block;
import enchia.time.main.block.MoonGrass1Block;
import enchia.time.main.block.MoonDoorBlock;
import enchia.time.main.block.MoonBlockdBlock;
import enchia.time.main.block.MoonBlockcBlock;
import enchia.time.main.block.MoonBlockbBlock;
import enchia.time.main.block.MobspawnerblockoBlock;
import enchia.time.main.block.MistarilleOreBlockBlock;
import enchia.time.main.block.MistarilleOreBlock;
import enchia.time.main.block.Minecraftyears100stoneBlock;
import enchia.time.main.block.Minecraftyears100leavesBlock;
import enchia.time.main.block.Minecraftyears100grassBlock;
import enchia.time.main.block.Minecraftyears100dirtBlock;
import enchia.time.main.block.MinecraftYears100LogBlock;
import enchia.time.main.block.Mcy400stairsBlock;
import enchia.time.main.block.Mcy400slabBlock;
import enchia.time.main.block.Mcy400logBlock;
import enchia.time.main.block.Mcy400grassBlock;
import enchia.time.main.block.Mcy400dirtBlock;
import enchia.time.main.block.Mcy25600PortalBlock;
import enchia.time.main.block.Mcy100leavesBlock;
import enchia.time.main.block.MantleBlock;
import enchia.time.main.block.MagicWoodBlock;
import enchia.time.main.block.MagicSugercaneBlock;
import enchia.time.main.block.MagicStairsBlock;
import enchia.time.main.block.MagicSlabBlock;
import enchia.time.main.block.MagicLogBlock;
import enchia.time.main.block.MagicLeavesBlock;
import enchia.time.main.block.MagicLeaves3Block;
import enchia.time.main.block.MagicLeaves2Block;
import enchia.time.main.block.MagicFenceGateBlock;
import enchia.time.main.block.MagicFenceBlock;
import enchia.time.main.block.MagicCauldronBlock;
import enchia.time.main.block.MagicBlockoBlock;
import enchia.time.main.block.MagentaGlassDoorBlock;
import enchia.time.main.block.MINECRAFTYEARS100WATERBlock;
import enchia.time.main.block.MCY409600PortalBlock;
import enchia.time.main.block.MCY400UndergroundPortalBlock;
import enchia.time.main.block.MCY400StoneBlock;
import enchia.time.main.block.MCY400PortalBlock;
import enchia.time.main.block.MCY400PlanksTarpDoorBlock;
import enchia.time.main.block.MCY400PlanksBlock;
import enchia.time.main.block.MCY400LeavesBlock;
import enchia.time.main.block.MCY400GroundPortalBlock;
import enchia.time.main.block.MCY400EmeraldOreBlock;
import enchia.time.main.block.MCY400DiamondOreBlock;
import enchia.time.main.block.MCY400DOORBlock;
import enchia.time.main.block.MCY1638400PortalBlock;
import enchia.time.main.block.MCY1600StoneBlock;
import enchia.time.main.block.MCY1600PortalBlock;
import enchia.time.main.block.MCY1600GrassBlock;
import enchia.time.main.block.MCY1600EmeraldOreBlock;
import enchia.time.main.block.MCY1600DirtBlock;
import enchia.time.main.block.MCY1600DiamondOreBlock;
import enchia.time.main.block.MCY102400StoneBlock;
import enchia.time.main.block.MCY102400SmoothStoneBlock;
import enchia.time.main.block.MCY102400PortalBlock;
import enchia.time.main.block.MCY102400GrassBlock;
import enchia.time.main.block.MCY102400DirtBlock;
import enchia.time.main.block.MCY100PortalBlock;
import enchia.time.main.block.MCY100PlanksTarpdoorBlock;
import enchia.time.main.block.MCY100PlanksStairsBlock;
import enchia.time.main.block.MCY100PlanksSlabBlock;
import enchia.time.main.block.MCY100PlanksFenceBlock;
import enchia.time.main.block.MCY100PlanksBlock;
import enchia.time.main.block.MCY100ObsidianBlock;
import enchia.time.main.block.MCY100LogBlock;
import enchia.time.main.block.MCY100GrassBlock;
import enchia.time.main.block.MCY100EmeraldOreBlock;
import enchia.time.main.block.MCY100DoorBlock;
import enchia.time.main.block.MCY100CoalOreBlock;
import enchia.time.main.block.MCY0PortalBlock;
import enchia.time.main.block.MC400PlanksFenceBlock;
import enchia.time.main.block.LuckyGlassBlock;
import enchia.time.main.block.LivinghellstoneBlock;
import enchia.time.main.block.LimeGreenCrystalBlock;
import enchia.time.main.block.LimeGlassDoorBlock;
import enchia.time.main.block.LightRockBlock;
import enchia.time.main.block.LightGreenGlassDoorBlock;
import enchia.time.main.block.LightGrayGlassDoorBlock;
import enchia.time.main.block.LightBlueGlassDoorBlock;
import enchia.time.main.block.JadeOreBlockBlock;
import enchia.time.main.block.JadeOreBlock;
import enchia.time.main.block.ItemBlockBlock;
import enchia.time.main.block.IchoriumOreBlock;
import enchia.time.main.block.IchoriumBlockBlock;
import enchia.time.main.block.IchorOreBlock;
import enchia.time.main.block.IchorBlockBlock;
import enchia.time.main.block.IceWaterBlock;
import enchia.time.main.block.IceTorchBlock;
import enchia.time.main.block.IcePlanksButtonBlock;
import enchia.time.main.block.IceGrassBlock;
import enchia.time.main.block.IceFlowerBlock;
import enchia.time.main.block.IceCrystalBlock;
import enchia.time.main.block.IceBricksBlock;
import enchia.time.main.block.IceBoxBlock;
import enchia.time.main.block.IceBookshelfBlock;
import enchia.time.main.block.IceBlueCrystalBlock;
import enchia.time.main.block.IceAltarBrickBlock;
import enchia.time.main.block.HypertmIceBlock;
import enchia.time.main.block.HydrangeaRedBlock;
import enchia.time.main.block.HugeCucturWoodBlock;
import enchia.time.main.block.HugeCucturStairsBlock;
import enchia.time.main.block.HugeCucturSlabBlock;
import enchia.time.main.block.HugeCucturPressurePlateBlock;
import enchia.time.main.block.HugeCucturPlanksBlock;
import enchia.time.main.block.HugeCucturLogBlock;
import enchia.time.main.block.HugeCucturLeavesBlock;
import enchia.time.main.block.HugeCucturFenceGateBlock;
import enchia.time.main.block.HugeCucturFenceBlock;
import enchia.time.main.block.HugeCucturButtonBlock;
import enchia.time.main.block.HellWoodBlock;
import enchia.time.main.block.HellLogBlock;
import enchia.time.main.block.HeavyGoldenSlabBlock;
import enchia.time.main.block.HeatstoneTorchBlock;
import enchia.time.main.block.HealthystoneorenetherBlock;
import enchia.time.main.block.HealthyStoneOreBlock;
import enchia.time.main.block.HardboneOreBlockBlock;
import enchia.time.main.block.HardboneOreBlock;
import enchia.time.main.block.GreenGlowstoneBlock;
import enchia.time.main.block.GreenEternalRedstoneLampBlock;
import enchia.time.main.block.GreenCrystalBlock;
import enchia.time.main.block.GrayGlassDoorBlock;
import enchia.time.main.block.GoldenDoorBlock;
import enchia.time.main.block.GoldenCoalOreBlock;
import enchia.time.main.block.GoldenBookShelfBlock;
import enchia.time.main.block.GoldenAppleBlockBlock;
import enchia.time.main.block.GlowstoneStairsBlock;
import enchia.time.main.block.GlowstoneSlabBlock;
import enchia.time.main.block.GlowstoneGlassBlock;
import enchia.time.main.block.GlowstoneBricksTrapdoorBlock;
import enchia.time.main.block.GlowstoneBricksDoorBlock;
import enchia.time.main.block.Glowshroom2Block;
import enchia.time.main.block.GlowingobsidianBlock;
import enchia.time.main.block.GlowingIceBlock;
import enchia.time.main.block.GlowStoneBrickBlock;
import enchia.time.main.block.GlowMushroomBlock;
import enchia.time.main.block.GlassWallBlock;
import enchia.time.main.block.GlassTarpDoorBlock;
import enchia.time.main.block.GlassStairsBlock;
import enchia.time.main.block.GlassSlabBlock;
import enchia.time.main.block.GlassFenceDoorBlock;
import enchia.time.main.block.GlassFenceBlock;
import enchia.time.main.block.GlassDoorBlock;
import enchia.time.main.block.GingerBlock;
import enchia.time.main.block.GhoulWoodBlock;
import enchia.time.main.block.GhoulStoneBlock;
import enchia.time.main.block.GhoulStairsBlock;
import enchia.time.main.block.GhoulSlabBlock;
import enchia.time.main.block.GhoulPressurePlateBlock;
import enchia.time.main.block.GhoulPlantBlock;
import enchia.time.main.block.GhoulPlant5Block;
import enchia.time.main.block.GhoulPlant4Block;
import enchia.time.main.block.GhoulPlant3Block;
import enchia.time.main.block.GhoulPlant2Block;
import enchia.time.main.block.GhoulPlanksBlock;
import enchia.time.main.block.GhoulPlains6Block;
import enchia.time.main.block.GhoulMatterBlock;
import enchia.time.main.block.GhoulLogBlock;
import enchia.time.main.block.GhoulLeavesBlock;
import enchia.time.main.block.GhoulLandBlock;
import enchia.time.main.block.GhoulLampBlock;
import enchia.time.main.block.GhoulItemPlant2Block;
import enchia.time.main.block.GhoulItemPlant1Block;
import enchia.time.main.block.GhoulFenceGateBlock;
import enchia.time.main.block.GhoulFenceBlock;
import enchia.time.main.block.GhoulButtonBlock;
import enchia.time.main.block.FrozenSandBlock;
import enchia.time.main.block.FrozenFlowerBlock;
import enchia.time.main.block.FrozenCobblestoneBlock;
import enchia.time.main.block.FrozenCoalOreBlock;
import enchia.time.main.block.FrozenCoalLampBlock;
import enchia.time.main.block.FrostyReedsBlock;
import enchia.time.main.block.FragileGhoulStoneBlock;
import enchia.time.main.block.ForzenGrassBlock;
import enchia.time.main.block.FlintBlockBlock;
import enchia.time.main.block.FishOreBlock;
import enchia.time.main.block.FireRockBlock;
import enchia.time.main.block.FireCobbleStoneBlock;
import enchia.time.main.block.Fire5Block;
import enchia.time.main.block.Fire4Block;
import enchia.time.main.block.Fire3Block;
import enchia.time.main.block.Fire2Block;
import enchia.time.main.block.Fire1Block;
import enchia.time.main.block.FinishBlockBlock;
import enchia.time.main.block.FakeStoneBlock;
import enchia.time.main.block.FakeDirtBlock;
import enchia.time.main.block.FakeCoalBlock;
import enchia.time.main.block.FakeBedrockBlock;
import enchia.time.main.block.EthereusLandBlock;
import enchia.time.main.block.EthereulPortalBlock;
import enchia.time.main.block.Ether6Block;
import enchia.time.main.block.Ether5Block;
import enchia.time.main.block.Ether4Block;
import enchia.time.main.block.Ether3Block;
import enchia.time.main.block.Ether2Block;
import enchia.time.main.block.EternalRedstoneLampBlock;
import enchia.time.main.block.EternalQuartzBlock;
import enchia.time.main.block.EmeraldABlock;
import enchia.time.main.block.DungeonSandstonpeBlock;
import enchia.time.main.block.DungeonSandstoneDoorBlock;
import enchia.time.main.block.DreamGrassBlock;
import enchia.time.main.block.DreamDirtBlock;
import enchia.time.main.block.DreamBedBlock;
import enchia.time.main.block.DimensionGemOreBlock;
import enchia.time.main.block.DesertWoodBlock;
import enchia.time.main.block.DesertStairsBlock;
import enchia.time.main.block.DesertSlabBlock;
import enchia.time.main.block.DesertPlanksButtonBlock;
import enchia.time.main.block.DesertPlanksBlock;
import enchia.time.main.block.DesertLogBlock;
import enchia.time.main.block.DesertFenceGateBlock;
import enchia.time.main.block.DesertFenceBlock;
import enchia.time.main.block.DesertEmeraldOreBlock;
import enchia.time.main.block.DesertDiamondOreBlock;
import enchia.time.main.block.DarkBrickBlock;
import enchia.time.main.block.CyanGlowstoneBlock;
import enchia.time.main.block.CyanGlassDoorBlock;
import enchia.time.main.block.CyanEternalRedstoneLampBlock;
import enchia.time.main.block.CucturBlock;
import enchia.time.main.block.CrystalOreBlockBlock;
import enchia.time.main.block.CrystalOreBlock;
import enchia.time.main.block.CrystalAltarBlock;
import enchia.time.main.block.CreeperOreBlock;
import enchia.time.main.block.CreeperEggBlock;
import enchia.time.main.block.CopperOreBlockBlock;
import enchia.time.main.block.CopperOreBlock;
import enchia.time.main.block.ControlleroffBlock;
import enchia.time.main.block.ControllerOnBlock;
import enchia.time.main.block.ConnectspawnblockoBlock;
import enchia.time.main.block.CompressGoldBlockBlock;
import enchia.time.main.block.ColdSteelOreBlock;
import enchia.time.main.block.ColdSteelBlockBlock;
import enchia.time.main.block.CloudBlock;
import enchia.time.main.block.ClearGlassPaneBlock;
import enchia.time.main.block.ClearGlassDoorBlock;
import enchia.time.main.block.ClearGlassBlock;
import enchia.time.main.block.ClassicWoodBlock;
import enchia.time.main.block.ClassicStoneBlock;
import enchia.time.main.block.ClassicStairsBlock;
import enchia.time.main.block.ClassicSlabBlock;
import enchia.time.main.block.ClassicPlanksButtonBlock;
import enchia.time.main.block.ClassicPlanksBlock;
import enchia.time.main.block.ClassicLogBlock;
import enchia.time.main.block.ClassicIronOreBlock;
import enchia.time.main.block.ClassicIronBlockBlock;
import enchia.time.main.block.ClassicGrassBlock;
import enchia.time.main.block.ClassicGoldenBlockBlock;
import enchia.time.main.block.ClassicFenceGateBlock;
import enchia.time.main.block.ClassicFenceBlock;
import enchia.time.main.block.ClassicDirtBlock;
import enchia.time.main.block.ClassicDiamondOreBlock;
import enchia.time.main.block.ClassicDiamondBlockBlock;
import enchia.time.main.block.ClassicCobbleStoneBlock;
import enchia.time.main.block.ChocolateLeavesBlock;
import enchia.time.main.block.ChocolateBlockBlock;
import enchia.time.main.block.CherryWoodBlock;
import enchia.time.main.block.CherryStairsBlock;
import enchia.time.main.block.CherrySlabBlock;
import enchia.time.main.block.CherryPlanksButtonBlock;
import enchia.time.main.block.CherryPlanksBlock;
import enchia.time.main.block.CherryLogBlock;
import enchia.time.main.block.CherryLeavesBlock;
import enchia.time.main.block.CherryLeaves2Block;
import enchia.time.main.block.CherryFenceGateBlock;
import enchia.time.main.block.CherryFenceBlock;
import enchia.time.main.block.ChaosCrystalOreBlock;
import enchia.time.main.block.CentellaBlock;
import enchia.time.main.block.CandyPortalFrameBlock;
import enchia.time.main.block.CandyPortalBlock;
import enchia.time.main.block.CandyGrassBlock;
import enchia.time.main.block.CandyCane6Block;
import enchia.time.main.block.CandyCane4Block;
import enchia.time.main.block.CandyCane3Block;
import enchia.time.main.block.CandyBrickBlock;
import enchia.time.main.block.CandyBlockBlock;
import enchia.time.main.block.CakeChocolateBlock;
import enchia.time.main.block.Cake7Block;
import enchia.time.main.block.Cake6Block;
import enchia.time.main.block.Cake5Block;
import enchia.time.main.block.Cake4Block;
import enchia.time.main.block.Cake3Block;
import enchia.time.main.block.Cake2Block;
import enchia.time.main.block.Cake1Block;
import enchia.time.main.block.CageBlock;
import enchia.time.main.block.CactusBlock;
import enchia.time.main.block.Cactus400Block;
import enchia.time.main.block.Cactus2Block;
import enchia.time.main.block.CLBlockBlock;
import enchia.time.main.block.BurningAltarBlock;
import enchia.time.main.block.BrownGlassDoorBlock;
import enchia.time.main.block.BreadblockBlock;
import enchia.time.main.block.BossspawnerblockoBlock;
import enchia.time.main.block.BossbrickBlock;
import enchia.time.main.block.BluesandstoneBlock;
import enchia.time.main.block.BlueSandBlock;
import enchia.time.main.block.BlueGlowstoneBlock;
import enchia.time.main.block.BlueEternalRedstoneLampBlock;
import enchia.time.main.block.BlueCutSandstoneBlock;
import enchia.time.main.block.BloodstoneblockBlock;
import enchia.time.main.block.BlockCouldRunBlock;
import enchia.time.main.block.BlackSandStoneBlock;
import enchia.time.main.block.BlackSandBlock;
import enchia.time.main.block.BlackGlowstoneBlock;
import enchia.time.main.block.BlackGlassDoorBlock;
import enchia.time.main.block.BlackEternalRedstoneLampBlock;
import enchia.time.main.block.BlackCutSandstoneBlock;
import enchia.time.main.block.BlackCrystalBlock;
import enchia.time.main.block.BigmushroomBlock;
import enchia.time.main.block.Bigmushroom2Block;
import enchia.time.main.block.BetaleavesBlock;
import enchia.time.main.block.BellFlowerBlock;
import enchia.time.main.block.BambooTarpDorrBlock;
import enchia.time.main.block.BambooPlanksButtonBlock;
import enchia.time.main.block.BambooLogWoodBlock;
import enchia.time.main.block.BambooLogStairsBlock;
import enchia.time.main.block.BambooLogSlabBlock;
import enchia.time.main.block.BambooLogPlanksBlock;
import enchia.time.main.block.BambooLogFenceGateBlock;
import enchia.time.main.block.BambooLogFenceBlock;
import enchia.time.main.block.BambooLogBlock;
import enchia.time.main.block.BambooLeavesBlock;
import enchia.time.main.block.BackPortalSkyBlock;
import enchia.time.main.block.BLUEgLASSdOORBlock;
import enchia.time.main.block.AquamarineOreBlockBlock;
import enchia.time.main.block.AquamarineOreBlock;
import enchia.time.main.block.AppleBlockBlock;
import enchia.time.main.block.AncientGlowstoneBlock;
import enchia.time.main.block.AncientBlock;
import enchia.time.main.block.AmethystOreBlockBlock;
import enchia.time.main.block.AmethystOreBlock;
import enchia.time.main.block.AmethystBricksBlock;
import enchia.time.main.block.AltarAlphaBlock;
import enchia.time.main.block.AcidBlock;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class TimeModBlocks {
	private static final List<Block> REGISTRY = new ArrayList<>();
	public static final Block TIME_MACHINE = register(new TimeMachineBlock());
	public static final Block USELESS_TIME_MACHINE = register(new UselessTimeMachineBlock());
	public static final Block MCY_100_PORTAL = register(new MCY100PortalBlock());
	public static final Block MCY_400_PORTAL = register(new MCY400PortalBlock());
	public static final Block MCY_1600_PORTAL = register(new MCY1600PortalBlock());
	public static final Block MCY_25600_PORTAL = register(new Mcy25600PortalBlock());
	public static final Block MCY_102400_PORTAL = register(new MCY102400PortalBlock());
	public static final Block MCY_409600_PORTAL = register(new MCY409600PortalBlock());
	public static final Block MCY_1638400_PORTAL = register(new MCY1638400PortalBlock());
	public static final Block NETHERANCIENT_PORTAL = register(new NetherancientPortalBlock());
	public static final Block RISER_STATUE = register(new RiserStatueBlock());
	public static final Block XP_LORD_STATUE = register(new XPLordStatueBlock());
	public static final Block FAKE_COAL = register(new FakeCoalBlock());
	public static final Block FROZEN_COAL_ORE = register(new FrozenCoalOreBlock());
	public static final Block COLD_STEEL_ORE = register(new ColdSteelOreBlock());
	public static final Block MORCANT_ORE = register(new MorcantOreBlock());
	public static final Block MISTARILLE_ORE = register(new MistarilleOreBlock());
	public static final Block TERAMERIAIUMORE = register(new TerameriaiumoreBlock());
	public static final Block SPRING_ORE = register(new SpringOreBlock());
	public static final Block COPPER_ORE = register(new CopperOreBlock());
	public static final Block JADE_ORE = register(new JadeOreBlock());
	public static final Block PERAFRIUM_ORE = register(new PerafriumOreBlock());
	public static final Block DESERT_EMERALD_ORE = register(new DesertEmeraldOreBlock());
	public static final Block DESERT_DIAMOND_ORE = register(new DesertDiamondOreBlock());
	public static final Block MCY_400_DIAMOND_ORE = register(new MCY400DiamondOreBlock());
	public static final Block MCY_400_EMERALD_ORE = register(new MCY400EmeraldOreBlock());
	public static final Block GOLDEN_COAL_ORE = register(new GoldenCoalOreBlock());
	public static final Block AMETHYST_ORE = register(new AmethystOreBlock());
	public static final Block ICHOR_ORE = register(new IchorOreBlock());
	public static final Block ICHORIUM_ORE = register(new IchoriumOreBlock());
	public static final Block AQUAMARINE_ORE = register(new AquamarineOreBlock());
	public static final Block CHAOS_CRYSTAL_ORE = register(new ChaosCrystalOreBlock());
	public static final Block MCY_100_COAL_ORE = register(new MCY100CoalOreBlock());
	public static final Block VITREOUS_ORE = register(new VitreousOreBlock());
	public static final Block MCY_1600_DIAMOND_ORE = register(new MCY1600DiamondOreBlock());
	public static final Block MCY_1600_EMERALD_ORE = register(new MCY1600EmeraldOreBlock());
	public static final Block HEALTHY_STONE_ORE = register(new HealthyStoneOreBlock());
	public static final Block MCY_100_EMERALD_ORE = register(new MCY100EmeraldOreBlock());
	public static final Block RUNE_ORE = register(new RuneOreBlock());
	public static final Block TIME_GEM_ORE = register(new TimeGemOreBlock());
	public static final Block DIMENSION_GEM_ORE = register(new DimensionGemOreBlock());
	public static final Block FISH_ORE = register(new FishOreBlock());
	public static final Block CLASSIC_DIAMOND_ORE = register(new ClassicDiamondOreBlock());
	public static final Block CLASSIC_IRON_ORE = register(new ClassicIronOreBlock());
	public static final Block HEALTHYSTONEORENETHER = register(new HealthystoneorenetherBlock());
	public static final Block NETHERONORE = register(new NetheronoreBlock());
	public static final Block WITHER_BONE_ORE = register(new WitherBoneOreBlock());
	public static final Block CREEPER_ORE = register(new CreeperOreBlock());
	public static final Block CRYSTAL_ORE = register(new CrystalOreBlock());
	public static final Block RED_CRYSTAL = register(new RedCrystalBlock());
	public static final Block WHITE_CRYSTAL = register(new WhiteCrystalBlock());
	public static final Block LIME_GREEN_CRYSTAL = register(new LimeGreenCrystalBlock());
	public static final Block PINK_CRYSTAL = register(new PinkCrystalBlock());
	public static final Block BLACK_CRYSTAL = register(new BlackCrystalBlock());
	public static final Block ICE_BLUE_CRYSTAL = register(new IceBlueCrystalBlock());
	public static final Block GREEN_CRYSTAL = register(new GreenCrystalBlock());
	public static final Block DREAM_GRASS = register(new DreamGrassBlock());
	public static final Block MCY_102400_GRASS = register(new MCY102400GrassBlock());
	public static final Block MINECRAFTYEARS_100GRASS = register(new Minecraftyears100grassBlock());
	public static final Block MCY_1600_GRASS = register(new MCY1600GrassBlock());
	public static final Block RUNE_GRASS = register(new RuneGrassBlock());
	public static final Block FORZEN_GRASS = register(new ForzenGrassBlock());
	public static final Block GHOUL_LAND = register(new GhoulLandBlock());
	public static final Block ETHEREUS_LAND = register(new EthereusLandBlock());
	public static final Block CAKE_CHOCOLATE = register(new CakeChocolateBlock());
	public static final Block CANDY_GRASS = register(new CandyGrassBlock());
	public static final Block CAKE_6 = register(new Cake6Block());
	public static final Block CAKE_7 = register(new Cake7Block());
	public static final Block TELEPORT_CAKE = register(new TeleportCakeBlock());
	public static final Block CAKE_2 = register(new Cake2Block());
	public static final Block CAKE_4 = register(new Cake4Block());
	public static final Block CAKE_3 = register(new Cake3Block());
	public static final Block CAKE_1 = register(new Cake1Block());
	public static final Block MCY_400GRASS = register(new Mcy400grassBlock());
	public static final Block SILENTIA_GRASS = register(new SilentiaGrassBlock());
	public static final Block CLASSIC_GRASS = register(new ClassicGrassBlock());
	public static final Block APPLE_BLOCK = register(new AppleBlockBlock());
	public static final Block GOLDEN_APPLE_BLOCK = register(new GoldenAppleBlockBlock());
	public static final Block DREAM_DIRT = register(new DreamDirtBlock());
	public static final Block MCY_400DIRT = register(new Mcy400dirtBlock());
	public static final Block NETHER_DIRT = register(new NetherDirtBlock());
	public static final Block MINECRAFTYEARS_100DIRT = register(new Minecraftyears100dirtBlock());
	public static final Block MCY_1600_DIRT = register(new MCY1600DirtBlock());
	public static final Block CLASSIC_DIRT = register(new ClassicDirtBlock());
	public static final Block SILENTIA_DIRT = register(new SilentiaDirtBlock());
	public static final Block CANDY_BLOCK = register(new CandyBlockBlock());
	public static final Block CAKE_5 = register(new Cake5Block());
	public static final Block CHOCOLATE_BLOCK = register(new ChocolateBlockBlock());
	public static final Block MOON_WARP_LEAVES = register(new MoonWarpLeavesBlock());
	public static final Block MOON_LEAVES = register(new MoonLeavesBlock());
	public static final Block MAGIC_LEAVES = register(new MagicLeavesBlock());
	public static final Block SAKURA_LEAVES = register(new SakuraLeavesBlock());
	public static final Block PHANTOM_LEAVES = register(new PhantomLeavesBlock());
	public static final Block MINECRAFTYEARS_100LEAVES = register(new Minecraftyears100leavesBlock());
	public static final Block MCY_100LEAVES = register(new Mcy100leavesBlock());
	public static final Block MCY_400_LEAVES = register(new MCY400LeavesBlock());
	public static final Block BAMBOO_LEAVES = register(new BambooLeavesBlock());
	public static final Block MAGIC_LEAVES_3 = register(new MagicLeaves3Block());
	public static final Block MAGIC_LEAVES_2 = register(new MagicLeaves2Block());
	public static final Block BETALEAVES = register(new BetaleavesBlock());
	public static final Block CHOCOLATE_LEAVES = register(new ChocolateLeavesBlock());
	public static final Block CHERRY_LEAVES = register(new CherryLeavesBlock());
	public static final Block CHERRY_LEAVES_2 = register(new CherryLeaves2Block());
	public static final Block GHOUL_LEAVES = register(new GhoulLeavesBlock());
	public static final Block CLOUD = register(new CloudBlock());
	public static final Block DESERT_WOOD = register(new DesertWoodBlock());
	public static final Block HELL_WOOD = register(new HellWoodBlock());
	public static final Block HELL_LOG = register(new HellLogBlock());
	public static final Block SAKURA_LOG = register(new SakuraLogBlock());
	public static final Block CHERRY_LOG = register(new CherryLogBlock());
	public static final Block MOON_WARP_LOG = register(new MoonWarpLogBlock());
	public static final Block DESERT_LOG = register(new DesertLogBlock());
	public static final Block CLASSIC_LOG = register(new ClassicLogBlock());
	public static final Block CLASSIC_WOOD = register(new ClassicWoodBlock());
	public static final Block HUGE_CUCTUR_WOOD = register(new HugeCucturWoodBlock());
	public static final Block SAKURA_WOOD = register(new SakuraWoodBlock());
	public static final Block MOON_WARP_WOOD = register(new MoonWarpWoodBlock());
	public static final Block HUGE_CUCTUR_LOG = register(new HugeCucturLogBlock());
	public static final Block BAMBOO_LOG_WOOD = register(new BambooLogWoodBlock());
	public static final Block MINECRAFT_YEARS_100_LOG = register(new MinecraftYears100LogBlock());
	public static final Block MCY_100_LOG = register(new MCY100LogBlock());
	public static final Block WAFFLE_STICK = register(new WaffleStickBlock());
	public static final Block MOON_LOG = register(new MoonLogBlock());
	public static final Block MCY_400LOG = register(new Mcy400logBlock());
	public static final Block MUSHROOMLOG = register(new MushroomlogBlock());
	public static final Block PHANTOM_LOG = register(new PhantomLogBlock());
	public static final Block MAGIC_WOOD = register(new MagicWoodBlock());
	public static final Block MAGIC_LOG = register(new MagicLogBlock());
	public static final Block BAMBOO_LOG = register(new BambooLogBlock());
	public static final Block CANDY_CANE_3 = register(new CandyCane3Block());
	public static final Block GHOUL_LOG = register(new GhoulLogBlock());
	public static final Block GHOUL_WOOD = register(new GhoulWoodBlock());
	public static final Block CANDY_CANE_4 = register(new CandyCane4Block());
	public static final Block CANDY_CANE_6 = register(new CandyCane6Block());
	public static final Block BIGMUSHROOM_2 = register(new Bigmushroom2Block());
	public static final Block BIGMUSHROOM = register(new BigmushroomBlock());
	public static final Block CLASSIC_PLANKS = register(new ClassicPlanksBlock());
	public static final Block MCY_100_PLANKS = register(new MCY100PlanksBlock());
	public static final Block SAKURA_PLANKS = register(new SakuraPlanksBlock());
	public static final Block MCY_400_PLANKS = register(new MCY400PlanksBlock());
	public static final Block FROZEN_SAND = register(new FrozenSandBlock());
	public static final Block PINK_SAND = register(new PinkSandBlock());
	public static final Block MCY_102400_STONE = register(new MCY102400StoneBlock());
	public static final Block MCY_102400_SMOOTH_STONE = register(new MCY102400SmoothStoneBlock());
	public static final Block SAND_102400 = register(new Sand102400Block());
	public static final Block HARDBONE_ORE = register(new HardboneOreBlock());
	public static final Block OLD_SAND = register(new OldSandBlock());
	public static final Block BLACK_CUT_SANDSTONE = register(new BlackCutSandstoneBlock());
	public static final Block BLACK_SAND_STONE = register(new BlackSandStoneBlock());
	public static final Block BLACK_SAND = register(new BlackSandBlock());
	public static final Block MANTLE = register(new MantleBlock());
	public static final Block MINECRAFTYEARS_100STONE = register(new Minecraftyears100stoneBlock());
	public static final Block CLASSIC_STONE = register(new ClassicStoneBlock());
	public static final Block CLASSIC_COBBLE_STONE = register(new ClassicCobbleStoneBlock());
	public static final Block LIGHT_ROCK = register(new LightRockBlock());
	public static final Block FAKE_BEDROCK = register(new FakeBedrockBlock());
	public static final Block ORIGIN_MEGMA = register(new OriginMegmaBlock());
	public static final Block MCY_1600_STONE = register(new MCY1600StoneBlock());
	public static final Block GHOUL_STONE = register(new GhoulStoneBlock());
	public static final Block FRAGILE_GHOUL_STONE = register(new FragileGhoulStoneBlock());
	public static final Block MCY_400_STONE = register(new MCY400StoneBlock());
	public static final Block BREADBLOCK = register(new BreadblockBlock());
	public static final Block CANDY_BRICK = register(new CandyBrickBlock());
	public static final Block AMETHYST_BRICKS = register(new AmethystBricksBlock());
	public static final Block DARK_BRICK = register(new DarkBrickBlock());
	public static final Block TRAP_2 = register(new Trap2Block());
	public static final Block TRAP_1 = register(new Trap1Block());
	public static final Block LIVINGHELLSTONE = register(new LivinghellstoneBlock());
	public static final Block ANCIENT_GLOWSTONE = register(new AncientGlowstoneBlock());
	public static final Block MOSSY_COBBLE_STONE = register(new MossyCobbleStoneBlock());
	public static final Block ICE_CRYSTAL = register(new IceCrystalBlock());
	public static final Block CLASSIC_DIAMOND_BLOCK = register(new ClassicDiamondBlockBlock());
	public static final Block CLASSIC_GOLDEN_BLOCK = register(new ClassicGoldenBlockBlock());
	public static final Block CLASSIC_IRON_BLOCK = register(new ClassicIronBlockBlock());
	public static final Block VITREOUS_BLOCK = register(new VitreousBlockBlock());
	public static final Block ICHORIUM_BLOCK = register(new IchoriumBlockBlock());
	public static final Block COMPRESS_GOLD_BLOCK = register(new CompressGoldBlockBlock());
	public static final Block BLOODSTONEBLOCK = register(new BloodstoneblockBlock());
	public static final Block MORCANT_ORE_BLOCK = register(new MorcantOreBlockBlock());
	public static final Block WHITEDIAMOND_ORE_BLOCK = register(new WhitediamondOreBlockBlock());
	public static final Block COPPER_ORE_BLOCK = register(new CopperOreBlockBlock());
	public static final Block HARDBONE_ORE_BLOCK = register(new HardboneOreBlockBlock());
	public static final Block MISTARILLE_ORE_BLOCK = register(new MistarilleOreBlockBlock());
	public static final Block JADE_ORE_BLOCK = register(new JadeOreBlockBlock());
	public static final Block TIN_ORE_BLOCK = register(new TinOreBlockBlock());
	public static final Block AMETHYST_ORE_BLOCK = register(new AmethystOreBlockBlock());
	public static final Block COLD_STEEL_BLOCK = register(new ColdSteelBlockBlock());
	public static final Block MUD_BLOCK = register(new MudBlockBlock());
	public static final Block AQUAMARINE_ORE_BLOCK = register(new AquamarineOreBlockBlock());
	public static final Block CRYSTAL_ORE_BLOCK = register(new CrystalOreBlockBlock());
	public static final Block XP_BLOCKO = register(new XpBlockoBlock());
	public static final Block MAGIC_BLOCKO = register(new MagicBlockoBlock());
	public static final Block ICHOR_BLOCK = register(new IchorBlockBlock());
	public static final Block FLINT_BLOCK = register(new FlintBlockBlock());
	public static final Block CANDY_PORTAL_FRAME = register(new CandyPortalFrameBlock());
	public static final Block MYSDOORINVABLEBLOCKO = register(new MysdoorinvableblockoBlock());
	public static final Block ALTAR_ALPHA = register(new AltarAlphaBlock());
	public static final Block MYSDOORINVKEYNEEDBLOCKO = register(new MysdoorinvkeyneedblockoBlock());
	public static final Block GOLDEN_BOOK_SHELF = register(new GoldenBookShelfBlock());
	public static final Block GLOWINGOBSIDIAN = register(new GlowingobsidianBlock());
	public static final Block BURNING_ALTAR = register(new BurningAltarBlock());
	public static final Block CLEAR_GLASS_PANE = register(new ClearGlassPaneBlock());
	public static final Block CLEAR_GLASS = register(new ClearGlassBlock());
	public static final Block DREAM_BED = register(new DreamBedBlock());
	public static final Block BOSSBRICK = register(new BossbrickBlock());
	public static final Block CONTROLLEROFF = register(new ControlleroffBlock());
	public static final Block EMERALD_A = register(new EmeraldABlock());
	public static final Block UNLUCKY_BLOCK = register(new UnluckyBlockBlock());
	public static final Block SCROLL_BENCH = register(new ScrollBenchBlock());
	public static final Block SEAWEEDS_DRYER = register(new SeaweedsDryerBlock());
	public static final Block RISER_ALTAR = register(new RiserAltarBlock());
	public static final Block RISER_LOOT = register(new RiserLootBlock());
	public static final Block MOON_BLOCKB = register(new MoonBlockbBlock());
	public static final Block CRYSTAL_ALTAR = register(new CrystalAltarBlock());
	public static final Block ANCIENT = register(new AncientBlock());
	public static final Block CAGE = register(new CageBlock());
	public static final Block XPALTAR = register(new XpaltarBlock());
	public static final Block ICE_BRICKS = register(new IceBricksBlock());
	public static final Block NETHERREACTOR = register(new NetherreactorBlock());
	public static final Block FIRE_1 = register(new Fire1Block());
	public static final Block FIRE_2 = register(new Fire2Block());
	public static final Block FIRE_3 = register(new Fire3Block());
	public static final Block FIRE_4 = register(new Fire4Block());
	public static final Block FIRE_5 = register(new Fire5Block());
	public static final Block SPRING = register(new SpringBlock());
	public static final Block PURE_WATER = register(new PureWaterBlock());
	public static final Block MINECRAFTYEARS_100_WATER = register(new MINECRAFTYEARS100WATERBlock());
	public static final Block ICE_WATER = register(new IceWaterBlock());
	public static final Block ACID = register(new AcidBlock());
	public static final Block GHOUL_FENCE = register(new GhoulFenceBlock());
	public static final Block GHOUL_FENCE_GATE = register(new GhoulFenceGateBlock());
	public static final Block GHOUL_PRESSURE_PLATE = register(new GhoulPressurePlateBlock());
	public static final Block DESERT_STAIRS = register(new DesertStairsBlock());
	public static final Block DESERT_SLAB = register(new DesertSlabBlock());
	public static final Block DESERT_FENCE = register(new DesertFenceBlock());
	public static final Block DESERT_FENCE_GATE = register(new DesertFenceGateBlock());
	public static final Block MAGIC_STAIRS = register(new MagicStairsBlock());
	public static final Block MAGIC_SLAB = register(new MagicSlabBlock());
	public static final Block MAGIC_FENCE = register(new MagicFenceBlock());
	public static final Block MAGIC_FENCE_GATE = register(new MagicFenceGateBlock());
	public static final Block BAMBOO_LOG_STAIRS = register(new BambooLogStairsBlock());
	public static final Block BAMBOO_LOG_SLAB = register(new BambooLogSlabBlock());
	public static final Block BAMBOO_LOG_FENCE = register(new BambooLogFenceBlock());
	public static final Block BAMBOO_LOG_FENCE_GATE = register(new BambooLogFenceGateBlock());
	public static final Block CLASSIC_STAIRS = register(new ClassicStairsBlock());
	public static final Block CLASSIC_SLAB = register(new ClassicSlabBlock());
	public static final Block CLASSIC_FENCE = register(new ClassicFenceBlock());
	public static final Block CLASSIC_FENCE_GATE = register(new ClassicFenceGateBlock());
	public static final Block HUGE_CUCTUR_STAIRS = register(new HugeCucturStairsBlock());
	public static final Block HUGE_CUCTUR_PLANKS = register(new HugeCucturPlanksBlock());
	public static final Block HUGE_CUCTUR_SLAB = register(new HugeCucturSlabBlock());
	public static final Block HUGE_CUCTUR_FENCE = register(new HugeCucturFenceBlock());
	public static final Block HUGE_CUCTUR_FENCE_GATE = register(new HugeCucturFenceGateBlock());
	public static final Block HUGE_CUCTUR_PRESSURE_PLATE = register(new HugeCucturPressurePlateBlock());
	public static final Block MCY_100_PLANKS_STAIRS = register(new MCY100PlanksStairsBlock());
	public static final Block MCY_100_PLANKS_SLAB = register(new MCY100PlanksSlabBlock());
	public static final Block MCY_100_PLANKS_FENCE = register(new MCY100PlanksFenceBlock());
	public static final Block MCY_400STAIRS = register(new Mcy400stairsBlock());
	public static final Block MCY_400SLAB = register(new Mcy400slabBlock());
	public static final Block MC_400_PLANKS_FENCE = register(new MC400PlanksFenceBlock());
	public static final Block CHERRY_STAIRS = register(new CherryStairsBlock());
	public static final Block CHERRY_SLAB = register(new CherrySlabBlock());
	public static final Block CHERRY_FENCE = register(new CherryFenceBlock());
	public static final Block CHERRY_FENCE_GATE = register(new CherryFenceGateBlock());
	public static final Block SAKURA_STAIRS = register(new SakuraStairsBlock());
	public static final Block SAKURA_SLAB = register(new SakuraSlabBlock());
	public static final Block SAKURA_FENCE = register(new SakuraFenceBlock());
	public static final Block SAKURA_PRESSURE_PLATE = register(new SakuraPressurePlateBlock());
	public static final Block TEAK_PRESSURE_PLATE = register(new TeakPressurePlateBlock());
	public static final Block SAKURA_FENCE_GATE = register(new SakuraFenceGateBlock());
	public static final Block GLOWSTONE_SLAB = register(new GlowstoneSlabBlock());
	public static final Block HEAVY_GOLDEN_SLAB = register(new HeavyGoldenSlabBlock());
	public static final Block GLOWSTONE_STAIRS = register(new GlowstoneStairsBlock());
	public static final Block MOON_WARP_STAIRS = register(new MoonWarpStairsBlock());
	public static final Block MOON_WARP_SLAB = register(new MoonWarpSlabBlock());
	public static final Block MOON_WARP_PRESSURE_PLATE = register(new MoonWarpPressurePlateBlock());
	public static final Block MOON_WARP_FENCE_GATE = register(new MoonWarpFenceGateBlock());
	public static final Block MOON_WARP_FENCE = register(new MoonWarpFenceBlock());
	public static final Block GHOUL_STAIRS = register(new GhoulStairsBlock());
	public static final Block GHOUL_SLAB = register(new GhoulSlabBlock());
	public static final Block SAKURA_TRAPDOOR = register(new SakuraTrapdoorBlock());
	public static final Block MCY_100_PLANKS_TARPDOOR = register(new MCY100PlanksTarpdoorBlock());
	public static final Block MCY_400_PLANKS_TARP_DOOR = register(new MCY400PlanksTarpDoorBlock());
	public static final Block GLOWSTONE_BRICKS_TRAPDOOR = register(new GlowstoneBricksTrapdoorBlock());
	public static final Block GLOWSTONE_BRICKS_DOOR = register(new GlowstoneBricksDoorBlock());
	public static final Block BAMBOO_TARP_DORR = register(new BambooTarpDorrBlock());
	public static final Block ICE_ALTAR_BRICK = register(new IceAltarBrickBlock());
	public static final Block MAGIC_SUGERCANE = register(new MagicSugercaneBlock());
	public static final Block STRAWBERRIES_PLANT = register(new StrawberriesPlantBlock());
	public static final Block MCY_100_GRASS = register(new MCY100GrassBlock());
	public static final Block ICE_GRASS = register(new IceGrassBlock());
	public static final Block SHURB = register(new ShurbBlock());
	public static final Block GLOW_MUSHROOM = register(new GlowMushroomBlock());
	public static final Block CENTELLA = register(new CentellaBlock());
	public static final Block WOODSIA = register(new WoodsiaBlock());
	public static final Block TURTLEHEAD = register(new TurtleheadBlock());
	public static final Block GLOWSHROOM_2 = register(new Glowshroom2Block());
	public static final Block WHITE_RUZOVA = register(new WhiteRuzovaBlock());
	public static final Block MOON_GRASS_3 = register(new MoonGrass3Block());
	public static final Block MOON_GRASS = register(new MoonGrassBlock());
	public static final Block ICE_FLOWER = register(new IceFlowerBlock());
	public static final Block CACTUS = register(new CactusBlock());
	public static final Block CACTUS_400 = register(new Cactus400Block());
	public static final Block FROSTY_REEDS = register(new FrostyReedsBlock());
	public static final Block GHOUL_PLANT = register(new GhoulPlantBlock());
	public static final Block ETHER_5 = register(new Ether5Block());
	public static final Block ETHER_6 = register(new Ether6Block());
	public static final Block ETHER_4 = register(new Ether4Block());
	public static final Block ETHER_3 = register(new Ether3Block());
	public static final Block ETHER_2 = register(new Ether2Block());
	public static final Block GHOUL_ITEM_PLANT_2 = register(new GhoulItemPlant2Block());
	public static final Block GHOUL_PLANT_2 = register(new GhoulPlant2Block());
	public static final Block GHOUL_ITEM_PLANT_1 = register(new GhoulItemPlant1Block());
	public static final Block GHOUL_PLAINS_6 = register(new GhoulPlains6Block());
	public static final Block GHOUL_PLANT_3 = register(new GhoulPlant3Block());
	public static final Block GHOUL_PLANT_5 = register(new GhoulPlant5Block());
	public static final Block GHOUL_PLANT_4 = register(new GhoulPlant4Block());
	public static final Block CACTUS_2 = register(new Cactus2Block());
	public static final Block CUCTUR = register(new CucturBlock());
	public static final Block FROZEN_FLOWER = register(new FrozenFlowerBlock());
	public static final Block HYDRANGEA_RED = register(new HydrangeaRedBlock());
	public static final Block PRAIRIE_SAGE = register(new PrairieSageBlock());
	public static final Block BELL_FLOWER = register(new BellFlowerBlock());
	public static final Block MOON_GRASS_1 = register(new MoonGrass1Block());
	public static final Block MOON_GRASS_4 = register(new MoonGrass4Block());
	public static final Block MOON_GRASS_5 = register(new MoonGrass5Block());
	public static final Block XP_BLOCK_OF_INFINITY = register(new XpBlockOfInfinityBlock());
	public static final Block MOON_PLANKS = register(new MoonPlanksBlock());
	public static final Block CHERRY_PLANKS = register(new CherryPlanksBlock());
	public static final Block GHOUL_PLANKS = register(new GhoulPlanksBlock());
	public static final Block DESERT_PLANKS = register(new DesertPlanksBlock());
	public static final Block MOON_WARP_PLANKS = register(new MoonWarpPlanksBlock());
	public static final Block BAMBOO_LOG_PLANKS = register(new BambooLogPlanksBlock());
	public static final Block FAKE_STONE = register(new FakeStoneBlock());
	public static final Block TIN_ORE = register(new TinOreBlock());
	public static final Block PLANKS_1 = register(new Planks1Block());
	public static final Block PLANKS_2 = register(new Planks2Block());
	public static final Block PLANKS_3 = register(new Planks3Block());
	public static final Block PLANKS_5 = register(new Planks5Block());
	public static final Block PLANKS_7 = register(new Planks7Block());
	public static final Block PLANKS_8 = register(new Planks8Block());
	public static final Block FAKE_DIRT = register(new FakeDirtBlock());
	public static final Block TIME_CHAOS_MACHINE = register(new TimeChaosMachineBlock());
	public static final Block MCY_102400_DIRT = register(new MCY102400DirtBlock());
	public static final Block MOON_BLOCKC = register(new MoonBlockcBlock());
	public static final Block MOON_BLOCKD = register(new MoonBlockdBlock());
	public static final Block SAND_ALTAR = register(new SandAltarBlock());
	public static final Block SAKURA_DOOR = register(new SakuraDoorBlock());
	public static final Block MCY_100_DOOR = register(new MCY100DoorBlock());
	public static final Block MCY_400_DOOR = register(new MCY400DOORBlock());
	public static final Block MOON_DOOR = register(new MoonDoorBlock());
	public static final Block GOLDEN_DOOR = register(new GoldenDoorBlock());
	public static final Block GLASS_DOOR = register(new GlassDoorBlock());
	public static final Block LIME_GLASS_DOOR = register(new LimeGlassDoorBlock());
	public static final Block RED_GLASS_DOOR = register(new RedGlassDoorBlock());
	public static final Block BLU_EG_LAS_SD_OOR = register(new BLUEgLASSdOORBlock());
	public static final Block LIGHT_BLUE_GLASS_DOOR = register(new LightBlueGlassDoorBlock());
	public static final Block YELLOW_GLASS_DOOR = register(new YellowGlassDoorBlock());
	public static final Block LIGHT_GREEN_GLASS_DOOR = register(new LightGreenGlassDoorBlock());
	public static final Block WHITE_GLASS_DOOR = register(new WhiteGlassDoorBlock());
	public static final Block PINK_GLASS_DOOR = register(new PinkGlassDoorBlock());
	public static final Block MAGENTA_GLASS_DOOR = register(new MagentaGlassDoorBlock());
	public static final Block BLACK_GLASS_DOOR = register(new BlackGlassDoorBlock());
	public static final Block CLEAR_GLASS_DOOR = register(new ClearGlassDoorBlock());
	public static final Block GRAY_GLASS_DOOR = register(new GrayGlassDoorBlock());
	public static final Block LIGHT_GRAY_GLASS_DOOR = register(new LightGrayGlassDoorBlock());
	public static final Block CYAN_GLASS_DOOR = register(new CyanGlassDoorBlock());
	public static final Block BROWN_GLASS_DOOR = register(new BrownGlassDoorBlock());
	public static final Block ORANGE_GLASS_DOOR = register(new OrangeGlassDoorBlock());
	public static final Block PURPLE_GLASS_DOOR = register(new PurpleGlassDoorBlock());
	public static final Block RANDOM_BLOCK = register(new RandomBlockBlock());
	public static final Block LUCKY_GLASS = register(new LuckyGlassBlock());
	public static final Block SNOW_GLASS = register(new SnowGlassBlock());
	public static final Block WIND_GLASS = register(new WindGlassBlock());
	public static final Block MUSHROOM_GLASS = register(new MushroomGlassBlock());
	public static final Block GLOWSTONE_GLASS = register(new GlowstoneGlassBlock());
	public static final Block GLASS_SLAB = register(new GlassSlabBlock());
	public static final Block GLASS_STAIRS = register(new GlassStairsBlock());
	public static final Block GLASS_FENCE = register(new GlassFenceBlock());
	public static final Block GLASS_FENCE_DOOR = register(new GlassFenceDoorBlock());
	public static final Block GLASS_WALL = register(new GlassWallBlock());
	public static final Block GLASS_TARP_DOOR = register(new GlassTarpDoorBlock());
	public static final Block ETERNAL_QUARTZ = register(new EternalQuartzBlock());
	public static final Block ICE_TORCH = register(new IceTorchBlock());
	public static final Block HEATSTONE_TORCH = register(new HeatstoneTorchBlock());
	public static final Block FIRE_ROCK = register(new FireRockBlock());
	public static final Block FIRE_COBBLE_STONE = register(new FireCobbleStoneBlock());
	public static final Block CHERRY_WOOD = register(new CherryWoodBlock());
	public static final Block FROZEN_COAL_LAMP = register(new FrozenCoalLampBlock());
	public static final Block BLACK_ETERNAL_REDSTONE_LAMP = register(new BlackEternalRedstoneLampBlock());
	public static final Block BLUE_ETERNAL_REDSTONE_LAMP = register(new BlueEternalRedstoneLampBlock());
	public static final Block CYAN_ETERNAL_REDSTONE_LAMP = register(new CyanEternalRedstoneLampBlock());
	public static final Block GREEN_ETERNAL_REDSTONE_LAMP = register(new GreenEternalRedstoneLampBlock());
	public static final Block ORANGE_ETERNAL_REDSTONE_LAMP = register(new OrangeEternalRedstoneLampBlock());
	public static final Block PINK_ETERNAL_REDSTONE_LAMP = register(new PinkEternalRedstoneLampBlock());
	public static final Block PURPLE_ETERNAL_REDSTONE_LAMP = register(new PurpleEternalRedstoneLampBlock());
	public static final Block GHOUL_LAMP = register(new GhoulLampBlock());
	public static final Block RED_ETERNAL_REDSTONE_LAMP = register(new RedEternalRedstoneLampBlock());
	public static final Block ETERNAL_REDSTONE_LAMP = register(new EternalRedstoneLampBlock());
	public static final Block GLOW_STONE_BRICK = register(new GlowStoneBrickBlock());
	public static final Block BLACK_GLOWSTONE = register(new BlackGlowstoneBlock());
	public static final Block RED_GLOWSTONE = register(new RedGlowstoneBlock());
	public static final Block BLUE_GLOWSTONE = register(new BlueGlowstoneBlock());
	public static final Block CYAN_GLOWSTONE = register(new CyanGlowstoneBlock());
	public static final Block GREEN_GLOWSTONE = register(new GreenGlowstoneBlock());
	public static final Block PINK_GLOWSTONE = register(new PinkGlowstoneBlock());
	public static final Block PURPLPPE_GLOWSTONE = register(new PurplppeGlowstoneBlock());
	public static final Block WHITE_GLOWSTONE = register(new WhiteGlowstoneBlock());
	public static final Block HYPERTM_ICE = register(new HypertmIceBlock());
	public static final Block YELLOW_MUSHROOM = register(new YellowMushroomBlock());
	public static final Block RED_MUSHROOM = register(new RedMushroomBlock());
	public static final Block SMOOTH_BLOCK = register(new SmoothBlockBlock());
	public static final Block MOSSY_STONE = register(new MossyStoneBlock());
	public static final Block MUSHROOM_LAMP = register(new MushroomLampBlock());
	public static final Block GLOWING_ICE = register(new GlowingIceBlock());
	public static final Block WIND_SAND = register(new WindSandBlock());
	public static final Block STONE_OF_THE_DEPTHS = register(new StoneOfTheDepthsBlock());
	public static final Block SNOW_SAND = register(new SnowSandBlock());
	public static final Block MUSHROOM_SAND = register(new MushroomSandBlock());
	public static final Block SPAWN_DUNGEON_25600_BLOCK = register(new SpawnDungeon25600BlockBlock());
	public static final Block CREEPER_EGG = register(new CreeperEggBlock());
	public static final Block TEAK_BOOKSHELF = register(new TeakBookshelfBlock());
	public static final Block ICE_BOOKSHELF = register(new IceBookshelfBlock());
	public static final Block STONE_GRASS = register(new StoneGrassBlock());
	public static final Block SAND_BLOCK_1 = register(new SandBlock1Block());
	public static final Block SANDSTONE_1 = register(new Sandstone1Block());
	public static final Block SANDSTONE_2 = register(new Sandstone2Block());
	public static final Block SANDSTONE_3 = register(new Sandstone3Block());
	public static final Block SANDSTONE_4 = register(new Sandstone4Block());
	public static final Block SANDSTONE_5 = register(new Sandstone5Block());
	public static final Block DUNGEON_SANDSTONPE = register(new DungeonSandstonpeBlock());
	public static final Block SAND_TRAP_1 = register(new SandTrap1Block());
	public static final Block SAND_TRAP_2 = register(new SandTrap2Block());
	public static final Block SAND_TRAP_3 = register(new SandTrap3Block());
	public static final Block SANDSTONE_6 = register(new Sandstone6Block());
	public static final Block SANDSTONE_7 = register(new Sandstone7Block());
	public static final Block SANDSTONE_8 = register(new Sandstone8Block());
	public static final Block SANDSTONE_9 = register(new Sandstone9Block());
	public static final Block SANDSTONE_10 = register(new Sandstone10Block());
	public static final Block SAND_2 = register(new Sand2Block());
	public static final Block PINK_SANDSTONE = register(new PinkSandstoneBlock());
	public static final Block PINK_CUT_SANDSTONE = register(new PinkCutSandstoneBlock());
	public static final Block PURPLE_SANDSTONE = register(new PurpleSandstoneBlock());
	public static final Block PURPLE_CUT_SANDSTONE = register(new PurpleCutSandstoneBlock());
	public static final Block BLUE_SAND = register(new BlueSandBlock());
	public static final Block BLUESANDSTONE = register(new BluesandstoneBlock());
	public static final Block BLUE_CUT_SANDSTONE = register(new BlueCutSandstoneBlock());
	public static final Block TIME_MACHINE_BLOCK = register(new TimeMachineBlockBlock());
	public static final Block QUARTZ_1 = register(new Quartz1Block());
	public static final Block QUARTZ_2 = register(new Quartz2Block());
	public static final Block QUARTZ_3 = register(new Quartz3Block());
	public static final Block QUARTZ_4 = register(new Quartz4Block());
	public static final Block QUARTZ = register(new QuartzBlock());
	public static final Block QUARTZ_6 = register(new Quartz6Block());
	public static final Block HUGE_CUCTUR_BUTTON = register(new HugeCucturButtonBlock());
	public static final Block MOON_WARP_BUTTON = register(new MoonWarpButtonBlock());
	public static final Block SAKURA_BUTTON = register(new SakuraButtonBlock());
	public static final Block TEAK_PLANKS_BUTTON = register(new TeakPlanksButtonBlock());
	public static final Block ICE_PLANKS_BUTTON = register(new IcePlanksButtonBlock());
	public static final Block BAMBOO_PLANKS_BUTTON = register(new BambooPlanksButtonBlock());
	public static final Block CLASSIC_PLANKS_BUTTON = register(new ClassicPlanksButtonBlock());
	public static final Block CHERRY_PLANKS_BUTTON = register(new CherryPlanksButtonBlock());
	public static final Block MOON_PLANKS_BUTTON = register(new MoonPlanksButtonBlock());
	public static final Block DESERT_PLANKS_BUTTON = register(new DesertPlanksButtonBlock());
	public static final Block GHOUL_BUTTON = register(new GhoulButtonBlock());
	public static final Block NETHERREACTOR_2 = register(new Netherreactor2Block());
	public static final Block MCY_100_OBSIDIAN = register(new MCY100ObsidianBlock());
	public static final Block TIMEMACHINEWALLLIGHT = register(new TimemachinewalllightBlock());
	public static final Block BACK_PORTAL_SKY = register(new BackPortalSkyBlock());
	public static final Block NETHER_GRASS = register(new NetherGrassBlock());
	public static final Block MUSHROOMTREEBLUE = register(new MushroomtreeblueBlock());
	public static final Block MUSHROOMTREEGREEN = register(new MushroomtreegreenBlock());
	public static final Block MUSHROOOOOOOM = register(new MushrooooooomBlock());
	public static final Block MAGIC_CAULDRON = register(new MagicCauldronBlock());
	public static final Block ICE_BOX = register(new IceBoxBlock());
	public static final Block SPRING_2 = register(new Spring2Block());
	public static final Block SPRING_3 = register(new Spring3Block());
	public static final Block PLANKS_9 = register(new Planks9Block());
	public static final Block PLANKS_1_0 = register(new Planks10Block());
	public static final Block CANDY_PORTAL = register(new CandyPortalBlock());
	public static final Block GINGER = register(new GingerBlock());
	public static final Block WASTE_BLOCK = register(new WasteBlockBlock());
	public static final Block RADOMBLOCKO = register(new RadomblockoBlock());
	public static final Block BOSSSPAWNERBLOCKO = register(new BossspawnerblockoBlock());
	public static final Block CONNECTSPAWNBLOCKO = register(new ConnectspawnblockoBlock());
	public static final Block MOBSPAWNERBLOCKO = register(new MobspawnerblockoBlock());
	public static final Block STRAWBERRY_BLOCK = register(new StrawberryBlockBlock());
	public static final Block STRAWBERRY_LOG_WOOD = register(new StrawberryLogWoodBlock());
	public static final Block STRAWBERRY_LOG_LOG = register(new StrawberryLogLogBlock());
	public static final Block STRAWBERRY_LOG_PLANKS = register(new StrawberryLogPlanksBlock());
	public static final Block STRAWBERRY_LOG_LEAVES = register(new StrawberryLogLeavesBlock());
	public static final Block STRAWBERRY_LOG_STAIRS = register(new StrawberryLogStairsBlock());
	public static final Block STRAWBERRY_LOG_SLAB = register(new StrawberryLogSlabBlock());
	public static final Block STRAWBERRY_LOG_FENCE = register(new StrawberryLogFenceBlock());
	public static final Block STRAWBERRY_LOG_FENCE_GATE = register(new StrawberryLogFenceGateBlock());
	public static final Block SWEET_GRASS = register(new SweetGrassBlock());
	public static final Block CL_BLOCK = register(new CLBlockBlock());
	public static final Block MCY_0_PORTAL = register(new MCY0PortalBlock());
	public static final Block CONTROLLER_ON = register(new ControllerOnBlock());
	public static final Block MCY_400_GROUND_PORTAL = register(new MCY400GroundPortalBlock());
	public static final Block FINISH_BLOCK = register(new FinishBlockBlock());
	public static final Block BLOCK_COULD_RUN = register(new BlockCouldRunBlock());
	public static final Block SNOWY_BLOCK = register(new SnowyBlockBlock());
	public static final Block POLYMERIZATION_ALTAR = register(new PolymerizationAltarBlock());
	public static final Block ITEM_BLOCK = register(new ItemBlockBlock());
	public static final Block DUNGEON_SANDSTONE_DOOR = register(new DungeonSandstoneDoorBlock());
	public static final Block STRAWBERRY_PLANKS_BUTTON = register(new StrawberryPlanksButtonBlock());
	public static final Block MCY_400_UNDERGROUND_PORTAL = register(new MCY400UndergroundPortalBlock());
	public static final Block HUGE_CUCTUR_LEAVES = register(new HugeCucturLeavesBlock());
	public static final Block ETHEREUL_PORTAL = register(new EthereulPortalBlock());
	public static final Block NEW_DREAM_BED = register(new NewDreamBedBlock());
	public static final Block GHOUL_MATTER = register(new GhoulMatterBlock());
	public static final Block TIME_MACHINE_WALL = register(new TimeMachineWallBlock());
	public static final Block SPACE_GEM_ORE = register(new SpaceGemOreBlock());
	public static final Block WHITEDIAMOND_ORE = register(new WhitediamondOreBlock());
	public static final Block FROZEN_COBBLESTONE = register(new FrozenCobblestoneBlock());

	private static Block register(Block block) {
		REGISTRY.add(block);
		return block;
	}

	@SubscribeEvent
	public static void registerBlocks(RegistryEvent.Register<Block> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Block[0]));
	}

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			RiserStatueBlock.registerRenderLayer();
			XPLordStatueBlock.registerRenderLayer();
			MCY400EmeraldOreBlock.registerRenderLayer();
			ChaosCrystalOreBlock.registerRenderLayer();
			MCY1600EmeraldOreBlock.registerRenderLayer();
			GhoulLandBlock.registerRenderLayer();
			EthereusLandBlock.registerRenderLayer();
			MoonLeavesBlock.registerRenderLayer();
			GhoulLogBlock.registerRenderLayer();
			GhoulWoodBlock.registerRenderLayer();
			GhoulStoneBlock.registerRenderLayer();
			FragileGhoulStoneBlock.registerRenderLayer();
			MCY400StoneBlock.registerRenderLayer();
			BloodstoneblockBlock.registerRenderLayer();
			MorcantOreBlockBlock.registerRenderLayer();
			WhitediamondOreBlockBlock.registerRenderLayer();
			CopperOreBlockBlock.registerRenderLayer();
			HardboneOreBlockBlock.registerRenderLayer();
			JadeOreBlockBlock.registerRenderLayer();
			TinOreBlockBlock.registerRenderLayer();
			AmethystOreBlockBlock.registerRenderLayer();
			AquamarineOreBlockBlock.registerRenderLayer();
			CrystalOreBlockBlock.registerRenderLayer();
			CandyPortalFrameBlock.registerRenderLayer();
			AltarAlphaBlock.registerRenderLayer();
			ClearGlassPaneBlock.registerRenderLayer();
			ClearGlassBlock.registerRenderLayer();
			ScrollBenchBlock.registerRenderLayer();
			SeaweedsDryerBlock.registerRenderLayer();
			RiserAltarBlock.registerRenderLayer();
			RiserLootBlock.registerRenderLayer();
			CrystalAltarBlock.registerRenderLayer();
			Fire1Block.registerRenderLayer();
			Fire2Block.registerRenderLayer();
			Fire3Block.registerRenderLayer();
			Fire4Block.registerRenderLayer();
			Fire5Block.registerRenderLayer();
			MCY100PlanksStairsBlock.registerRenderLayer();
			MCY100PlanksSlabBlock.registerRenderLayer();
			MCY100PlanksFenceBlock.registerRenderLayer();
			Mcy400stairsBlock.registerRenderLayer();
			Mcy400slabBlock.registerRenderLayer();
			MC400PlanksFenceBlock.registerRenderLayer();
			GhoulStairsBlock.registerRenderLayer();
			GhoulSlabBlock.registerRenderLayer();
			SakuraTrapdoorBlock.registerRenderLayer();
			MCY100PlanksTarpdoorBlock.registerRenderLayer();
			MCY400PlanksTarpDoorBlock.registerRenderLayer();
			GlowstoneBricksTrapdoorBlock.registerRenderLayer();
			GlowstoneBricksDoorBlock.registerRenderLayer();
			BambooTarpDorrBlock.registerRenderLayer();
			IceAltarBrickBlock.registerRenderLayer();
			MagicSugercaneBlock.registerRenderLayer();
			StrawberriesPlantBlock.registerRenderLayer();
			MCY100GrassBlock.registerRenderLayer();
			IceGrassBlock.registerRenderLayer();
			ShurbBlock.registerRenderLayer();
			GlowMushroomBlock.registerRenderLayer();
			CentellaBlock.registerRenderLayer();
			WoodsiaBlock.registerRenderLayer();
			TurtleheadBlock.registerRenderLayer();
			Glowshroom2Block.registerRenderLayer();
			WhiteRuzovaBlock.registerRenderLayer();
			MoonGrass3Block.registerRenderLayer();
			MoonGrassBlock.registerRenderLayer();
			IceFlowerBlock.registerRenderLayer();
			CactusBlock.registerRenderLayer();
			Cactus400Block.registerRenderLayer();
			FrostyReedsBlock.registerRenderLayer();
			GhoulPlantBlock.registerRenderLayer();
			Ether5Block.registerRenderLayer();
			Ether6Block.registerRenderLayer();
			Ether4Block.registerRenderLayer();
			Ether3Block.registerRenderLayer();
			Ether2Block.registerRenderLayer();
			GhoulItemPlant2Block.registerRenderLayer();
			GhoulPlant2Block.registerRenderLayer();
			GhoulItemPlant1Block.registerRenderLayer();
			GhoulPlains6Block.registerRenderLayer();
			GhoulPlant3Block.registerRenderLayer();
			GhoulPlant5Block.registerRenderLayer();
			GhoulPlant4Block.registerRenderLayer();
			Cactus2Block.registerRenderLayer();
			CucturBlock.registerRenderLayer();
			FrozenFlowerBlock.registerRenderLayer();
			HydrangeaRedBlock.registerRenderLayer();
			PrairieSageBlock.registerRenderLayer();
			BellFlowerBlock.registerRenderLayer();
			MoonGrass1Block.registerRenderLayer();
			MoonGrass4Block.registerRenderLayer();
			MoonGrass5Block.registerRenderLayer();
			GhoulPlanksBlock.registerRenderLayer();
			SakuraDoorBlock.registerRenderLayer();
			MCY100DoorBlock.registerRenderLayer();
			MCY400DOORBlock.registerRenderLayer();
			MoonDoorBlock.registerRenderLayer();
			GoldenDoorBlock.registerRenderLayer();
			GlassDoorBlock.registerRenderLayer();
			LimeGlassDoorBlock.registerRenderLayer();
			RedGlassDoorBlock.registerRenderLayer();
			BLUEgLASSdOORBlock.registerRenderLayer();
			LightBlueGlassDoorBlock.registerRenderLayer();
			YellowGlassDoorBlock.registerRenderLayer();
			LightGreenGlassDoorBlock.registerRenderLayer();
			WhiteGlassDoorBlock.registerRenderLayer();
			PinkGlassDoorBlock.registerRenderLayer();
			MagentaGlassDoorBlock.registerRenderLayer();
			BlackGlassDoorBlock.registerRenderLayer();
			ClearGlassDoorBlock.registerRenderLayer();
			GrayGlassDoorBlock.registerRenderLayer();
			LightGrayGlassDoorBlock.registerRenderLayer();
			CyanGlassDoorBlock.registerRenderLayer();
			BrownGlassDoorBlock.registerRenderLayer();
			OrangeGlassDoorBlock.registerRenderLayer();
			PurpleGlassDoorBlock.registerRenderLayer();
			LuckyGlassBlock.registerRenderLayer();
			SnowGlassBlock.registerRenderLayer();
			WindGlassBlock.registerRenderLayer();
			MushroomGlassBlock.registerRenderLayer();
			GlowstoneGlassBlock.registerRenderLayer();
			GlassSlabBlock.registerRenderLayer();
			GlassStairsBlock.registerRenderLayer();
			GlassFenceBlock.registerRenderLayer();
			GlassFenceDoorBlock.registerRenderLayer();
			GlassWallBlock.registerRenderLayer();
			GlassTarpDoorBlock.registerRenderLayer();
			IceTorchBlock.registerRenderLayer();
			HeatstoneTorchBlock.registerRenderLayer();
			FrozenCoalLampBlock.registerRenderLayer();
			GhoulLampBlock.registerRenderLayer();
			SpawnDungeon25600BlockBlock.registerRenderLayer();
			TeakPlanksButtonBlock.registerRenderLayer();
			IcePlanksButtonBlock.registerRenderLayer();
			BambooPlanksButtonBlock.registerRenderLayer();
			ClassicPlanksButtonBlock.registerRenderLayer();
			CherryPlanksButtonBlock.registerRenderLayer();
			MoonPlanksButtonBlock.registerRenderLayer();
			DesertPlanksButtonBlock.registerRenderLayer();
			MagicCauldronBlock.registerRenderLayer();
			IceBoxBlock.registerRenderLayer();
			Spring2Block.registerRenderLayer();
			CandyPortalBlock.registerRenderLayer();
			GingerBlock.registerRenderLayer();
			RadomblockoBlock.registerRenderLayer();
			MCY400GroundPortalBlock.registerRenderLayer();
			DungeonSandstoneDoorBlock.registerRenderLayer();
			StrawberryPlanksButtonBlock.registerRenderLayer();
			MCY400UndergroundPortalBlock.registerRenderLayer();
			GhoulMatterBlock.registerRenderLayer();
		}

		@SubscribeEvent
		public static void blockColorLoad(ColorHandlerEvent.Block event) {
			DreamGrassBlock.blockColorLoad(event);
			MCY102400GrassBlock.blockColorLoad(event);
			Minecraftyears100grassBlock.blockColorLoad(event);
			MCY1600GrassBlock.blockColorLoad(event);
			RuneGrassBlock.blockColorLoad(event);
			CandyGrassBlock.blockColorLoad(event);
			Mcy400grassBlock.blockColorLoad(event);
			SilentiaGrassBlock.blockColorLoad(event);
			ClassicGrassBlock.blockColorLoad(event);
			PhantomLeavesBlock.blockColorLoad(event);
			MagicLeaves3Block.blockColorLoad(event);
			MagicLeaves2Block.blockColorLoad(event);
			MCY100GrassBlock.blockColorLoad(event);
			NetherGrassBlock.blockColorLoad(event);
			StrawberryLogLeavesBlock.blockColorLoad(event);
			SweetGrassBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(ColorHandlerEvent.Item event) {
			DreamGrassBlock.itemColorLoad(event);
			MCY102400GrassBlock.itemColorLoad(event);
			Minecraftyears100grassBlock.itemColorLoad(event);
			RuneGrassBlock.itemColorLoad(event);
			CandyGrassBlock.itemColorLoad(event);
			Mcy400grassBlock.itemColorLoad(event);
			SilentiaGrassBlock.itemColorLoad(event);
			ClassicGrassBlock.itemColorLoad(event);
			PhantomLeavesBlock.itemColorLoad(event);
			MagicLeaves3Block.itemColorLoad(event);
			MagicLeaves2Block.itemColorLoad(event);
			MCY100GrassBlock.itemColorLoad(event);
			NetherGrassBlock.itemColorLoad(event);
			StrawberryLogLeavesBlock.itemColorLoad(event);
			SweetGrassBlock.itemColorLoad(event);
		}
	}
}
